In [1]:
import numpy as np

# Understanding Numpy 

NumPy, or "Numerical Python", is a Python package most utilized in scientific computing. Many mathematical operations performed in NumPy are faster than in native Python, so it is ideal for highly demanding mathematical applications, such as Machine Learning.


## Basics

In [42]:
#Creates a nx1 array
n = 15
arr = np.arange(n)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
#Transforms np arrays to lists.
larr = arr.tolist()
larr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [58]:
# create a 3d zeros array
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
#transforms a array into a matrix
mat = np.matrix(arr)
mat

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## Arrays

In [74]:
#Creating an array from a list
#
# Just create a list of numbers, and pass it as a parameter for
# np.array()
#
alist = [1,2,3]
arr = np.array(alist)
arr

array([1, 2, 3])

In [78]:
# Creating an array of zeros
#
n = 5
arr = np.zeros(n)
arr

array([0., 0., 0., 0., 0.])

In [80]:
# Creating an array that goes from 0 to n
#
n = 10
arr = np.arange(n)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
# You can create an array that goes from n to k too
n = 10
k = 100
arr = np.arange(n,k)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [92]:
# You can create an array that goes from n to k
# in any number of steps
#
n = 0
k = 1
steps = 100
arr = np.linspace(n,k,steps)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

That is a very good example of how numerical computing just has difficulty in counting floating-point numbers!

In [107]:
# Suppose you want to make a logarithmic array of any base (in this case, 10),
# going from one number (0) to another (1) with a number of steps (10).
arr = np.logspace(0,1,10,base=10.0)
arr

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [113]:
# Create a nxn array of zeros
#
n = 3
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [119]:
# Creating a nxnxn cube of 1's
# astype() sets the array with integer elements
n = 3
cube = np.zeros((n,n,n)).astype(int) + 1
cube

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [151]:
# Again, you can set the data type in the NumPy arrays. 
# You can specify it using the "dtype" parameter in the methods.
# 
arr = np.zeros(2,dtype=np.float16) + 25.334234232327843274329
arr

array([25.33, 25.33], dtype=float16)

In [201]:
# You can reshape any array into another dimensions array. 
# Just remember, the numbers in the reshape must multiply 
# to equal the number of elements in the array. 
# For example, 3*3*3 = 27, so we can reshape it in that form.

# reshape (number_of_matrix,line_number,column_number)

arr1d = np.arange(27)
arr3d = arr1d.reshape((3,3,3))
#arr3d = np.reshape(arr1d, (3,3,3))
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [197]:
# you can do the inverse too with ravel
arr = arr3d.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [205]:
# You can see the dimensions of the array with the shape attribute.
arr.shape

(27,)